# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'drupal7'

# The runtime the application uses.
type: 'php:7.2'

# Configuration of the build of this application.
build:
  flavor: composer

# The build-time dependencies of the app.
dependencies:
  php:
    "drush/drush": "^8.0"

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    drupal7: 'mysqldb:drupal7'

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

        '/sites/figueroa/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/figueroa/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/figueroa/files/(css|js)':
                    expires: 2w

        '/sites/aircooled/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/aircooled/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/aircooled/files/(css|js)':
                    expires: 2w

        '/sites/eheart/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/eheart/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/eheart/files/(css|js)':
                    expires: 2w
# The size of the persistent disk of the application (in MB).
disk: 1024

# The mounts that will be performed when the package is deployed.


mounts:
  '/docroot/sites/default/files': 'shared:files/default'
  '/docroot/sites/aircooled/files': 'shared:files/aircooled'
  '/docroot/sites/eheart/files': 'shared:files/eheart'
  '/docroot/sites/figueroa/files': 'shared:files/figueroa'
  "/tmp": "shared:files/tmp/7"
  "/private": "shared:files/private/7"

# The hooks executed at various points in the lifecycle of the application.
hooks:
  deploy: |
    set -e
    cd web
    drush -y updatedb

crons:
    drupal:
        spec: '*/20 * * * *'
        cmd: 'cd docroot ; drush core-cron'


# Added for New Relic
#runtime:
    #extensions:
        #- newrelic
