https://{default}/:
  type: upstream
  upstream: drupal8:http
  primary: null
  id: null
  attributes: {}
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
https://el-hincho.com/:
  type: upstream
  upstream: drupal8:http
  cache:
      enabled: true
      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
https://drupal7.{default}/:
  type: upstream
  upstream: drupal7:http
  primary: null
  id: null
  attributes: {}
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
