# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: "mysql:10.0"
    disk: 2048
    configuration:
        schemas:
            - hinchodb
            - drupal7db
        endpoints:
            hincho:
                default_schema: hinchodb
                privileges:
                    hinchodb: admin
            drupal7:
                default_schema: drupal7db
                privileges:
                    drupal7db: admin

cache:
    type: redis:6.0
